release:
  prerelease: false

builds:
  - binary: limp
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.buildTime={{.Date}}`.

brews:
  - name: limp
    tap:
      owner: nderjung
      name: homebrew-tap
    homepage: "https://github.com/nderjung/limp/"
    description: "limp is a tool which LIMits standard input which has been Piped to it"

archives:
  - format: tar.gz

nfpms:
  - license: BSD-3-Clause
    maintainer: Alexander Jung
    homepage: https://github.com/nderjung/limp/
    description: "limp is a tool which LIMits standard input which has been Piped to it"
    formats:
      - rpm
      - deb

dockers:
  -
    binaries:
      - limp
    dockerfile: Dockerfile
    # todo: on 1.0 remove 'v' prefix
    image_templates:
      - "ndrjng/limp:latest"
      - "ndrjng/limp:{{ .Tag }}"
      - "ndrjng/limp:v{{ .Major }}"
      - "ndrjng/limp:v{{ .Major }}.{{ .Minor }}"
